import BackgroundLayers from "./components/BackgroundLayers";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="relative bg-white">
				<BackgroundLayers position="top" />
				<div className="h-full mx-auto flex items-center flex-col py-4 gap-16 max-w-[1440px] lg:px-16 px-4">
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
